//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Game/Scripts/Managers/InputManager/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""a3b6d5df-6891-45bb-88c5-50cb79e72cd8"",
            ""actions"": [
                {
                    ""name"": ""MOVE"",
                    ""type"": ""Value"",
                    ""id"": ""7c17ac3c-e02f-492a-978a-0c5d702dedc7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SPELL1"",
                    ""type"": ""Button"",
                    ""id"": ""eaa58f24-6d61-4a42-ab31-bca04734bca4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SPELL2"",
                    ""type"": ""Button"",
                    ""id"": ""e9f597fe-e57f-4a84-a4bc-f3864deec0b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SPELL3"",
                    ""type"": ""Button"",
                    ""id"": ""209a2219-9b7d-494a-a18e-b2a386a6dcee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SPELL4"",
                    ""type"": ""Button"",
                    ""id"": ""62004ec4-9988-49b3-b314-24a785d4d108"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SPELL5"",
                    ""type"": ""Button"",
                    ""id"": ""c91a7e07-7d09-4f0c-88b3-d9cac2d720d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BASIC1"",
                    ""type"": ""Button"",
                    ""id"": ""37f4a17f-d250-4508-8704-e3d9c9313d58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BASIC2"",
                    ""type"": ""Button"",
                    ""id"": ""b77a11c7-cebe-4941-a40c-cbcffd9736ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BASIC3"",
                    ""type"": ""Button"",
                    ""id"": ""833bd6fe-a902-42e5-a1c7-78870c56cc6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BASIC4"",
                    ""type"": ""Button"",
                    ""id"": ""474c7075-502e-433d-99d0-a8b7a30ea444"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PAUSE"",
                    ""type"": ""Button"",
                    ""id"": ""98e5439a-f3a1-4832-9c81-686835a1b76f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""INTERACT"",
                    ""type"": ""Button"",
                    ""id"": ""45a4c7ac-838a-4118-beca-f0af771f6c39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8563ce34-db10-4f6f-95d3-ed29701aef9c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVE"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""42cc37b0-999e-4c5b-b244-9283fce1ed29"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0530440a-ee5d-41bc-aa05-82df90ab99ae"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""07947851-e719-409a-b51e-5995e2d86e5e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7cca195f-d33f-4c63-acbd-80920a5215b3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b67c06ad-5177-458c-8d66-32d674957753"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPELL1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d110d76-d883-4f87-a568-e72a9497990d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPELL2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65980194-b05c-43d5-943f-5bb1315a7405"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPELL3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""996ec375-d1a5-4b95-83be-1e420d11175f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPELL4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""536f0207-35cd-4af6-a82b-689f10920416"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPELL5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f39d57b-e72f-446b-87de-da6cb24c1073"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BASIC1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddded17a-9465-4ac7-8e76-3dd456d58b71"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BASIC2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78b904b1-7c76-48ed-a659-6b801c802093"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BASIC3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2011402b-a279-41e6-b02f-00a6c888d8d8"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BASIC4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ee5f77d-1479-43d3-8360-811dd874623c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PAUSE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b432880-f8b5-4852-a0a7-3e646cbb07c4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""INTERACT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_MOVE = m_Game.FindAction("MOVE", throwIfNotFound: true);
        m_Game_SPELL1 = m_Game.FindAction("SPELL1", throwIfNotFound: true);
        m_Game_SPELL2 = m_Game.FindAction("SPELL2", throwIfNotFound: true);
        m_Game_SPELL3 = m_Game.FindAction("SPELL3", throwIfNotFound: true);
        m_Game_SPELL4 = m_Game.FindAction("SPELL4", throwIfNotFound: true);
        m_Game_SPELL5 = m_Game.FindAction("SPELL5", throwIfNotFound: true);
        m_Game_BASIC1 = m_Game.FindAction("BASIC1", throwIfNotFound: true);
        m_Game_BASIC2 = m_Game.FindAction("BASIC2", throwIfNotFound: true);
        m_Game_BASIC3 = m_Game.FindAction("BASIC3", throwIfNotFound: true);
        m_Game_BASIC4 = m_Game.FindAction("BASIC4", throwIfNotFound: true);
        m_Game_PAUSE = m_Game.FindAction("PAUSE", throwIfNotFound: true);
        m_Game_INTERACT = m_Game.FindAction("INTERACT", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private IGameActions m_GameActionsCallbackInterface;
    private readonly InputAction m_Game_MOVE;
    private readonly InputAction m_Game_SPELL1;
    private readonly InputAction m_Game_SPELL2;
    private readonly InputAction m_Game_SPELL3;
    private readonly InputAction m_Game_SPELL4;
    private readonly InputAction m_Game_SPELL5;
    private readonly InputAction m_Game_BASIC1;
    private readonly InputAction m_Game_BASIC2;
    private readonly InputAction m_Game_BASIC3;
    private readonly InputAction m_Game_BASIC4;
    private readonly InputAction m_Game_PAUSE;
    private readonly InputAction m_Game_INTERACT;
    public struct GameActions
    {
        private @InputActions m_Wrapper;
        public GameActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MOVE => m_Wrapper.m_Game_MOVE;
        public InputAction @SPELL1 => m_Wrapper.m_Game_SPELL1;
        public InputAction @SPELL2 => m_Wrapper.m_Game_SPELL2;
        public InputAction @SPELL3 => m_Wrapper.m_Game_SPELL3;
        public InputAction @SPELL4 => m_Wrapper.m_Game_SPELL4;
        public InputAction @SPELL5 => m_Wrapper.m_Game_SPELL5;
        public InputAction @BASIC1 => m_Wrapper.m_Game_BASIC1;
        public InputAction @BASIC2 => m_Wrapper.m_Game_BASIC2;
        public InputAction @BASIC3 => m_Wrapper.m_Game_BASIC3;
        public InputAction @BASIC4 => m_Wrapper.m_Game_BASIC4;
        public InputAction @PAUSE => m_Wrapper.m_Game_PAUSE;
        public InputAction @INTERACT => m_Wrapper.m_Game_INTERACT;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void SetCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterface != null)
            {
                @MOVE.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMOVE;
                @MOVE.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMOVE;
                @MOVE.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMOVE;
                @SPELL1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL1;
                @SPELL1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL1;
                @SPELL1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL1;
                @SPELL2.started -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL2;
                @SPELL2.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL2;
                @SPELL2.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL2;
                @SPELL3.started -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL3;
                @SPELL3.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL3;
                @SPELL3.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL3;
                @SPELL4.started -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL4;
                @SPELL4.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL4;
                @SPELL4.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL4;
                @SPELL5.started -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL5;
                @SPELL5.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL5;
                @SPELL5.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnSPELL5;
                @BASIC1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC1;
                @BASIC1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC1;
                @BASIC1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC1;
                @BASIC2.started -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC2;
                @BASIC2.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC2;
                @BASIC2.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC2;
                @BASIC3.started -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC3;
                @BASIC3.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC3;
                @BASIC3.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC3;
                @BASIC4.started -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC4;
                @BASIC4.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC4;
                @BASIC4.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnBASIC4;
                @PAUSE.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPAUSE;
                @PAUSE.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPAUSE;
                @PAUSE.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPAUSE;
                @INTERACT.started -= m_Wrapper.m_GameActionsCallbackInterface.OnINTERACT;
                @INTERACT.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnINTERACT;
                @INTERACT.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnINTERACT;
            }
            m_Wrapper.m_GameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MOVE.started += instance.OnMOVE;
                @MOVE.performed += instance.OnMOVE;
                @MOVE.canceled += instance.OnMOVE;
                @SPELL1.started += instance.OnSPELL1;
                @SPELL1.performed += instance.OnSPELL1;
                @SPELL1.canceled += instance.OnSPELL1;
                @SPELL2.started += instance.OnSPELL2;
                @SPELL2.performed += instance.OnSPELL2;
                @SPELL2.canceled += instance.OnSPELL2;
                @SPELL3.started += instance.OnSPELL3;
                @SPELL3.performed += instance.OnSPELL3;
                @SPELL3.canceled += instance.OnSPELL3;
                @SPELL4.started += instance.OnSPELL4;
                @SPELL4.performed += instance.OnSPELL4;
                @SPELL4.canceled += instance.OnSPELL4;
                @SPELL5.started += instance.OnSPELL5;
                @SPELL5.performed += instance.OnSPELL5;
                @SPELL5.canceled += instance.OnSPELL5;
                @BASIC1.started += instance.OnBASIC1;
                @BASIC1.performed += instance.OnBASIC1;
                @BASIC1.canceled += instance.OnBASIC1;
                @BASIC2.started += instance.OnBASIC2;
                @BASIC2.performed += instance.OnBASIC2;
                @BASIC2.canceled += instance.OnBASIC2;
                @BASIC3.started += instance.OnBASIC3;
                @BASIC3.performed += instance.OnBASIC3;
                @BASIC3.canceled += instance.OnBASIC3;
                @BASIC4.started += instance.OnBASIC4;
                @BASIC4.performed += instance.OnBASIC4;
                @BASIC4.canceled += instance.OnBASIC4;
                @PAUSE.started += instance.OnPAUSE;
                @PAUSE.performed += instance.OnPAUSE;
                @PAUSE.canceled += instance.OnPAUSE;
                @INTERACT.started += instance.OnINTERACT;
                @INTERACT.performed += instance.OnINTERACT;
                @INTERACT.canceled += instance.OnINTERACT;
            }
        }
    }
    public GameActions @Game => new GameActions(this);
    public interface IGameActions
    {
        void OnMOVE(InputAction.CallbackContext context);
        void OnSPELL1(InputAction.CallbackContext context);
        void OnSPELL2(InputAction.CallbackContext context);
        void OnSPELL3(InputAction.CallbackContext context);
        void OnSPELL4(InputAction.CallbackContext context);
        void OnSPELL5(InputAction.CallbackContext context);
        void OnBASIC1(InputAction.CallbackContext context);
        void OnBASIC2(InputAction.CallbackContext context);
        void OnBASIC3(InputAction.CallbackContext context);
        void OnBASIC4(InputAction.CallbackContext context);
        void OnPAUSE(InputAction.CallbackContext context);
        void OnINTERACT(InputAction.CallbackContext context);
    }
}
